#!/usr/bin/env python
import sys, os, re
from subprocess import check_output
commit_message_filepath = sys.argv[1]

current_branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode('utf8')

TEMPLATES = ('bugfix', 'feature', 'hotfix', 'issue')

for template in TEMPLATES:
    if current_branch.startswith(template):
        match = re.match(template + '.*?(\d+).*?', current_branch)
        if match:
            issue_number = match.group(1)
            with open(commit_message_filepath, 'r+') as f:
                content = f.read()
                f.seek(0, 0)
                f.write("postmat-%s: %s" % (issue_number, content))